export type Screen =
    | "menu"
    | "play"
    | "settings"
    | "howto"
    | "credits"
    | "single"
    | "private"
    | "public"
    | "privateLobby"
    | "publicQueue"
    | "game"
    | "leaderboard"
    | "login"
    | "lobbyFull";